# Generated by Django 5.2.15 on 2026-06-11 15:55

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.fields.json
import django.utils.timezone
import pgvector.django.indexes
import pgvector.django.vector
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CreateExtension('vector'),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('parent_container_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_container_versions', to='trackables.version')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='ContainerVersion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trackables.version',),
        ),
        migrations.CreateModel(
            name='VersionedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(blank=True, db_index=True, max_length=32)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type_data', models.JSONField(blank=True, default=dict)),
                ('ai_analysis_status', models.CharField(blank=True, choices=[('', 'Not Applicable'), ('pending', 'Pending Analysis'), ('processing', 'Processing'), ('completed', 'Analysis Complete'), ('failed', 'Analysis Failed'), ('skipped', 'Analysis Skipped')], default='', max_length=20)),
                ('ai_analysis_date', models.DateTimeField(blank=True, null=True)),
                ('semantic_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('path', models.CharField(blank=True, default='', max_length=1000)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('parent_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_containers', to='trackables.versionedentity')),
            ],
            options={
                'verbose_name_plural': 'versioned entities',
            },
        ),
        migrations.AddField(
            model_name='version',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='trackables.versionedentity'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('general', 'General Task'), ('review', 'Review Task'), ('approval', 'Approval Required'), ('development', 'Development'), ('testing', 'Testing'), ('documentation', 'Documentation'), ('bug_fix', 'Bug Fix'), ('feature', 'Feature Implementation'), ('maintenance', 'Maintenance'), ('deployment', 'Deployment')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('review', 'In Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('assigned_to', models.CharField(blank=True, help_text='User ID or email of assignee', max_length=100)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='trackables.task')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_tasks', to='trackables.version')),
                ('versioned_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_tasks', to='trackables.versionedentity')),
            ],
            options={
                'ordering': ['-priority', 'due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Symlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symlinks', to='trackables.version')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symlinks', to='trackables.versionedentity')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContainerReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_name', models.CharField(max_length=64)),
                ('symlink_name', models.CharField(max_length=64)),
                ('container_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='trackables.version')),
                ('resolved_version', models.ForeignKey(blank=True, help_text='Current symlink target (refreshed on demand)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currently_referenced_in_containers', to='trackables.version')),
                ('symlink_version', models.ForeignKey(help_text='Version the symlink pointed to when this container version was created', on_delete=django.db.models.deletion.CASCADE, related_name='referenced_in_containers', to='trackables.version')),
                ('referenced_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_references', to='trackables.versionedentity')),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trackables.versionedentity',),
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trackables.versionedentity',),
        ),
        migrations.AddIndex(
            model_name='versionedentity',
            index=models.Index(condition=models.Q(('entity_type', 'container')), fields=['path'], name='entity_path_idx'),
        ),
        migrations.AddIndex(
            model_name='versionedentity',
            index=models.Index(condition=models.Q(('entity_type', 'container')), fields=['path', 'depth'], name='entity_path_depth_idx'),
        ),
        migrations.AddIndex(
            model_name='versionedentity',
            index=models.Index(condition=models.Q(('ai_analysis_status', 'pending')), fields=['ai_analysis_status'], name='entity_ai_pending_idx'),
        ),
        migrations.AddIndex(
            model_name='versionedentity',
            index=models.Index(django.db.models.fields.json.KeyTextTransform('media_type', 'type_data'), condition=models.Q(('entity_type', 'media_asset')), name='entity_media_type_idx'),
        ),
        migrations.AddIndex(
            model_name='versionedentity',
            index=django.contrib.postgres.indexes.GinIndex(fields=['type_data'], name='entity_type_data_gin'),
        ),
        migrations.AddIndex(
            model_name='versionedentity',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['semantic_embedding'], m=16, name='entity_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddConstraint(
            model_name='versionedentity',
            constraint=models.CheckConstraint(condition=models.Q(('entity_type', 'container'), ('parent_container__isnull', True), _connector='OR'), name='parent_only_on_containers'),
        ),
        migrations.AddIndex(
            model_name='version',
            index=models.Index(fields=['created_at'], name='version_created_idx'),
        ),
        migrations.AddIndex(
            model_name='version',
            index=django.contrib.postgres.indexes.GinIndex(fields=['data'], name='version_data_gin'),
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.UniqueConstraint(fields=('entity', 'version_number'), name='unique_version_per_entity'),
        ),
        migrations.AddConstraint(
            model_name='symlink',
            constraint=models.UniqueConstraint(fields=('entity', 'name'), name='unique_symlink_per_entity'),
        ),
        migrations.AddIndex(
            model_name='containerreference',
            index=models.Index(fields=['referenced_entity', 'symlink_name'], name='trackables__referen_3186be_idx'),
        ),
        migrations.AddConstraint(
            model_name='containerreference',
            constraint=models.UniqueConstraint(fields=('container_version', 'reference_name'), name='unique_reference_per_container_version'),
        ),
        migrations.AddField(
            model_name='task',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container_tasks', to='trackables.container'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'assigned_to'], name='trackables__status_af9fb0_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date', 'status'], name='trackables__due_dat_b9c3c9_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['parent_task', 'status'], name='trackables__parent__eda325_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['versioned_entity', 'status'], name='trackables__version_389fb4_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['version', 'status'], name='trackables__version_295dbf_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['container', 'status'], name='trackables__contain_da253e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority', 'due_date'], name='trackables__priorit_34326c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_at'], name='trackables__created_2ec1a5_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='task_tags_gin'),
        ),
    ]
