# Generated by Django 5.2.15 on 2026-06-11 16:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRecipe',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trackables.versionedentity',),
        ),
        migrations.CreateModel(
            name='LoraAdapter',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trackables.versionedentity',),
        ),
        migrations.CreateModel(
            name='ModelCheckpoint',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trackables.versionedentity',),
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trackables.versionedentity',),
        ),
        migrations.AddField(
            model_name='version',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='version',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='versionedentity',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='containerreference',
            name='referenced_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='container_references', to='trackables.versionedentity'),
        ),
        migrations.AlterField(
            model_name='containerreference',
            name='resolved_version',
            field=models.ForeignKey(blank=True, help_text='Current symlink target (refreshed on demand; cache only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currently_referenced_in_containers', to='trackables.version'),
        ),
        migrations.AlterField(
            model_name='containerreference',
            name='symlink_version',
            field=models.ForeignKey(help_text='Version the symlink pointed to when this container version was created', on_delete=django.db.models.deletion.RESTRICT, related_name='referenced_in_containers', to='trackables.version'),
        ),
        migrations.AlterField(
            model_name='symlink',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='symlinks', to='trackables.version'),
        ),
        migrations.CreateModel(
            name='SymlinkEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symlink_events', to='trackables.versionedentity')),
                ('new_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='trackables.version')),
                ('old_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='trackables.version')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity', 'name', 'created_at'], name='trackables__entity__8de9fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='VersionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('from_version', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='downstream_links', to='trackables.version')),
                ('to_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstream_links', to='trackables.version')),
            ],
            options={
                'indexes': [models.Index(fields=['from_version', 'role'], name='trackables__from_ve_6afa58_idx'), models.Index(fields=['to_version', 'role'], name='trackables__to_vers_ef7016_idx')],
                'constraints': [models.UniqueConstraint(fields=('from_version', 'to_version', 'role'), name='unique_version_link')],
            },
        ),
    ]
