# Generated by Django 5.2.15 on 2026-06-11 18:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackables', '0002_generationrecipe_loraadapter_modelcheckpoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trackables.versionedentity',),
        ),
        migrations.CreateModel(
            name='EntityRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(db_index=True, max_length=32)),
                ('confidence', models.FloatField(default=1.0)),
                ('source', models.CharField(choices=[('user', 'User'), ('ai', 'AI suggested')], default='user', max_length=8)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_relations', to='trackables.versionedentity')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_relations', to='trackables.versionedentity')),
            ],
            options={
                'indexes': [models.Index(fields=['entity', 'role'], name='relation_entity_role_idx'), models.Index(fields=['asset', 'role'], name='relation_asset_role_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'entity', 'role'), name='unique_asset_entity_role')],
            },
        ),
    ]
