# Generated by Django 5.2.15 on 2026-06-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackables', '0003_board_entityrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartCollection',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trackables.versionedentity',),
        ),
        migrations.RemoveConstraint(
            model_name='versionedentity',
            name='parent_only_on_containers',
        ),
        migrations.AddConstraint(
            model_name='versionedentity',
            constraint=models.CheckConstraint(condition=models.Q(('entity_type', 'container'), ('entity_type', 'entity'), ('parent_container__isnull', True), _connector='OR'), name='parent_only_on_containers'),
        ),
    ]
