# Generated by Django 5.2.15 on 2026-06-13 01:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackables', '0004_smartcollection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DependencyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(choices=[('uses', 'Uses'), ('depends_on', 'Depends On'), ('imports', 'Imports'), ('references', 'References'), ('extends', 'Extends')], db_index=True, default='uses', max_length=32)),
                ('role', models.CharField(blank=True, help_text='Contextual role: "material", "texture", "library", "template", etc.', max_length=64)),
                ('source_version', models.ForeignKey(help_text='Version that has the dependency (e.g., the model using a texture)', on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='trackables.version')),
                ('target_version', models.ForeignKey(help_text='Version being used/referenced (pinned for reproducibility)', on_delete=django.db.models.deletion.RESTRICT, related_name='used_by', to='trackables.version')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='dependencylink',
            index=models.Index(fields=['source_version', 'relationship_type'], name='trackables__source__7ed6d2_idx'),
        ),
        migrations.AddIndex(
            model_name='dependencylink',
            index=models.Index(fields=['target_version'], name='trackables__target__ab4edd_idx'),
        ),
        migrations.AddIndex(
            model_name='dependencylink',
            index=models.Index(fields=['relationship_type'], name='trackables__relatio_aee2bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='dependencylink',
            constraint=models.UniqueConstraint(fields=('source_version', 'target_version', 'relationship_type'), name='unique_dependency_link'),
        ),
    ]
