# Generated by Django 5.2.15 on 2026-06-13 19:42
#
# Proxy-only migration: ImageAnnotation adds no DB table (it is a VersionedEntity
# proxy, like Board/SmartCollection). The autodetector also wanted to restate the
# unrelated `parent_only_on_containers` constraint (a Django-version representation
# churn that fails against pre-existing dev data); that drift is intentionally left
# out of this feature migration.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackables', '0005_add_dependency_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnnotation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trackables.versionedentity',),
        ),
    ]
