# Promote project membership from type_data.project_code to a real self-FK.
#
# Hand-written (not autogenerated) so the autodetector's unrelated re-statement
# of the `parent_only_on_containers` constraint stays out — same intentional
# drift documented in 0006. The FK targets the project row by `code`
# (db_column='project_code'), so the new column holds the same value that lived
# in type_data; 0008 backfills it.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackables', '0006_imageannotation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionedentity',
            name='project',
            field=models.ForeignKey(
                blank=True,
                null=True,
                db_column='project_code',
                limit_choices_to={'entity_type': 'project'},
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='entities',
                to='trackables.versionedentity',
                to_field='code',
            ),
        ),
    ]
