# Generated by Django 5.2.15 on 2026-07-17 16:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackables', '0008_backfill_project_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityReferenceSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.CharField(help_text="Named slot, e.g. 'turnaround', 'ref_sheet', 'model'.", max_length=64)),
                ('policy', models.CharField(choices=[('approved', 'Approved'), ('latest', 'Latest'), ('pinned', 'Pinned to specific version')], default='approved', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='RunIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('node_pins', models.JSONField(default=dict, help_text="Per-node pinned URI(s). Single: {node_id: 'nexus8://code@vN'}. Query set: {node_id: ['nexus8://code@vN', ...]}.")),
                ('params', models.JSONField(default=dict, help_text='Parameter values from the chosen Control Surface View.')),
                ('seed', models.IntegerField(blank=True, null=True)),
                ('armed_pins', models.JSONField(default=list, help_text='Labels of Pin nodes armed for this run (default empty = keep nothing).')),
                ('output_bindings', models.JSONField(default=list, help_text='Snapshot of attachment.output_bindings at intent creation time.')),
                ('on_ambiguity', models.CharField(choices=[('fail', 'Fail — never guess'), ('first', 'Use first candidate'), ('fan_out', 'Fan out — one run per candidate')], default='fail', max_length=16)),
                ('engine_run_id', models.CharField(blank=True, help_text='nodegraph run_id, set when nodegraph accepts the intent.', max_length=256)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_process', models.CharField(blank=True, help_text="Production stage value (e.g. 'storyboard') for process-level attachment.", max_length=64)),
                ('level', models.CharField(choices=[('process', 'Process-level (default for all assets in this process)'), ('asset', 'Asset-level (pinned to one specific asset)'), ('container', 'Container-level (pinned to a container)')], default='process', max_length=16)),
                ('mode', models.CharField(choices=[('iterate', 'Iterate (new version of this asset)'), ('derive', 'Derive (new linked asset)'), ('custom', 'Custom bindings')], default='iterate', max_length=16)),
                ('view_name', models.CharField(blank=True, help_text='Name of the Control Surface View that exposes parameters.', max_length=128)),
                ('graph_interface', models.JSONField(default=dict, help_text="Snapshot of the workflow's scanned nexus8 interface: {nodes: [AssetNode...], views: [{name, params}...]}.")),
                ('output_bindings', models.JSONField(default=list, help_text="Declared output bindings: [{slot, target, nameTemplate?, process?}]. target is 'new_version_of_self', 'new_asset', or 'discard'.")),
            ],
        ),
        migrations.CreateModel(
            name='NodegraphWorkflow',
            fields=[],
            options={'proxy': True, 'indexes': [], 'constraints': []},
            bases=('trackables.versionedentity',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[],
            options={'proxy': True, 'indexes': [], 'constraints': []},
            bases=('trackables.versionedentity',),
        ),
        migrations.AddField(
            model_name='entityreferenceslot',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='The asset assigned to this slot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='trackables.versionedentity'),
        ),
        migrations.AddField(
            model_name='entityreferenceslot',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_slots', to='trackables.versionedentity'),
        ),
        migrations.AddField(
            model_name='entityreferenceslot',
            name='pinned_version',
            field=models.ForeignKey(blank=True, help_text="Exact version for 'pinned' policy.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='trackables.version'),
        ),
        migrations.AddField(
            model_name='entityreferenceslot',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='runintent',
            name='batch_version',
            field=models.ForeignKey(blank=True, help_text='The run-batch ContainerVersion created when nodegraph executes this intent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='trackables.version'),
        ),
        migrations.AddField(
            model_name='runintent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='runintent',
            name='target_asset',
            field=models.ForeignKey(help_text="The asset this run targets (the 'Self' node resolves to this).", on_delete=django.db.models.deletion.PROTECT, related_name='run_intents', to='trackables.versionedentity'),
        ),
        migrations.AddField(
            model_name='workflowattachment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowattachment',
            name='target_entity',
            field=models.ForeignKey(blank=True, help_text='Set for asset- or container-level attachment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_attachments', to='trackables.versionedentity'),
        ),
        migrations.AddField(
            model_name='workflowattachment',
            name='workflow_version',
            field=models.ForeignKey(blank=True, help_text="Pinned workflow version; null means resolve 'latest' at run time.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='trackables.version'),
        ),
        migrations.AddField(
            model_name='runintent',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intents', to='trackables.workflowattachment'),
        ),
        migrations.AddField(
            model_name='workflowattachment',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='trackables.nodegraphworkflow'),
        ),
        migrations.AddIndex(
            model_name='entityreferenceslot',
            index=models.Index(fields=['entity'], name='refslot_entity_idx'),
        ),
        migrations.AddConstraint(
            model_name='entityreferenceslot',
            constraint=models.UniqueConstraint(fields=('entity', 'slot'), name='unique_entity_reference_slot'),
        ),
        migrations.AddIndex(
            model_name='runintent',
            index=models.Index(fields=['target_asset', 'status'], name='intent_asset_status_idx'),
        ),
        migrations.AddIndex(
            model_name='runintent',
            index=models.Index(fields=['attachment', 'status'], name='intent_attachment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='runintent',
            index=models.Index(fields=['status', 'created_at'], name='intent_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowattachment',
            index=models.Index(fields=['target_entity'], name='attachment_entity_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowattachment',
            index=models.Index(fields=['target_process'], name='attachment_process_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowattachment',
            index=models.Index(fields=['workflow'], name='attachment_workflow_idx'),
        ),
    ]
