# Generated by Django 5.2.15 on 2026-07-29 00:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackables', '0013_entityrelation_type_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['-version_number', '-variation_number']},
        ),
        migrations.RemoveConstraint(
            model_name='version',
            name='unique_version_per_entity',
        ),
        migrations.AddField(
            model_name='version',
            name='variation_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.UniqueConstraint(fields=('entity', 'version_number', 'variation_number'), name='unique_version_variation_per_entity'),
        ),
    ]
