# Generated by Claude on 2026-08-01 for SRED Phase 1.2
#
# Repaired 2026-08-06: the original AddIndex/RunSQL referenced columns that do
# not exist on EntityRelation (source_id / source_entity_type /
# target_entity_type) and could never apply. The (asset, role) lookup is
# already covered by relation_asset_role_idx; the only index this migration
# needs to add is the expression index on type_data->>'layer_id'.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackables', '0014_add_variation_number_to_version'),
    ]

    operations = [
        # Fast "track for (video, layer)" lookup: expression index on the
        # layer_id key inside type_data, partial over mask_track relations.
        # entity_type='mask_track' itself needs no schema change — it is just
        # a new value in the entity_type CharField.
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS idx_mask_track_layer_id
            ON trackables_entityrelation ((type_data->>'layer_id'))
            WHERE role = 'mask_track';
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_mask_track_layer_id;
            """,
        ),
    ]
