# Generated by Claude on 2026-08-01 for SRED Phase 1.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackables', '0014_add_variation_number_to_version'),
    ]

    operations = [
        # Add database index for fast mask track lookup by (source_video_id, layer_id)
        # Used by Phase 1.3 to find or create tracks, and Phase 1.4 timeline to fetch track metadata.
        # The actual entity_type='mask_track' value does not require a schema change;
        # it is just a new value in the entity_type CharField.
        migrations.AddIndex(
            model_name='entityrelation',
            index=models.Index(
                fields=['source_id', 'role'],
                condition=models.Q(
                    source_entity_type='video',
                    target_entity_type='mask_track',
                    role='mask_track'
                ),
                name='idx_mask_track_by_source_video',
            ),
        ),
        # Index for finding tracks by layer_id (stored in type_data)
        # Used by corrections loop and candidate selection
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS idx_mask_track_layer_id
            ON trackables_entityrelation ((type_data->>'layer_id'))
            WHERE target_entity_type = 'mask_track' AND role = 'mask_track';
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_mask_track_layer_id;
            """
        ),
    ]
