# Generated by Django 5.2.15 on 2026-08-06 20:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackables', '0015_mask_track_entity_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaskTrack',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trackables.versionedentity',),
        ),
        migrations.CreateModel(
            name='OperationJob',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('op', models.CharField(db_index=True, max_length=32)),
                ('layer_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('working', 'Working'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=16)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('modal_call_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('result_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_op_jobs', to='trackables.versionedentity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_op_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['asset', 'op', 'layer_id'], name='trackables__asset_i_c58c46_idx')],
            },
        ),
    ]
