# Generated by Django 5.2.15 on 2026-08-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackables', '0016_masktrack_operationjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('working', 'Working'), ('ingesting', 'Ingesting'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=16),
        ),
    ]
