"""
Django settings for nexus8 project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Overridable via NEXUS8_SECRET_KEY; the insecure default is for local dev only.
SECRET_KEY = os.environ.get(
    'NEXUS8_SECRET_KEY',
    'django-insecure-6$b6fd%n6wchehrcl6r*lkc27bf-j((-#_o$-zc9j17b$g^*^9',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('NEXUS8_DEBUG', '1') == '1'

ALLOWED_HOSTS = os.environ.get('NEXUS8_ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'drf_spectacular',
    'django_filters',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # profiling
    'silk',
    # nexus models
    'trackables',
    'discussions',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # debugging and profiling
    'silk.middleware.SilkyMiddleware',
]

ROOT_URLCONF = 'nexus8.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },

    },
    
]

WSGI_APPLICATION = 'nexus8.wsgi.application'


# Database — PostgreSQL is the only supported backend (recursive CTEs, GIN
# indexes, and pgvector are load-bearing). Configure via NEXUS8_DB_* env vars.
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('NEXUS8_DB_NAME', 'nexus8'),
        'USER': os.environ.get('NEXUS8_DB_USER', ''),
        'PASSWORD': os.environ.get('NEXUS8_DB_PASSWORD', ''),
        'HOST': os.environ.get('NEXUS8_DB_HOST', 'localhost'),
        'PORT': os.environ.get('NEXUS8_DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True






BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_collected') 
    # You can name 'staticfiles_collected' whatever you prefer, e.g., 'static_deploy'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Uploaded media (originals + generated thumbnail pyramid)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# CORS — the Vite dev server proxies /trackables, /discussions and /media to
# Django, so CORS is only needed when the SPA talks to Django directly.
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]
CORS_ALLOW_CREDENTIALS = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Dev-open mode: authenticate every API request as a shared "dev" user so the
# SPA needs no login flow. Only honored when DEBUG; set NEXUS8_DEV_OPEN=0 to
# exercise real auth locally.
NEXUS8_DEV_OPEN = DEBUG and os.environ.get('NEXUS8_DEV_OPEN', '1') == '1'

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

if NEXUS8_DEV_OPEN:
    REST_FRAMEWORK['DEFAULT_AUTHENTICATION_CLASSES'] = [
        'nexus8.dev_auth.DevAutoAuthentication',
    ]

# DRF Spectacular settings for API documentation
SPECTACULAR_SETTINGS = {
    'TITLE': 'Nexus8 Trackables API',
    'DESCRIPTION': 'Comprehensive API for managing hierarchical containers, versions, and references',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}
