# Generated by Django 5.2.15 on 2026-06-11 15:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trackables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('discussion_type', models.CharField(choices=[('general', 'General Discussion'), ('issue', 'Issue/Bug Report'), ('feature_request', 'Feature Request'), ('review', 'Code/Asset Review'), ('question', 'Question'), ('decision', 'Decision Required')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=15)),
                ('created_by', models.CharField(help_text='Username of discussion creator', max_length=100)),
                ('assigned_to', models.CharField(blank=True, help_text='Username of assigned person', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags for categorization')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('participants', models.JSONField(blank=True, default=list, help_text='List of usernames who participated')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container_discussions', to='trackables.container')),
                ('container_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container_version_discussions', to='trackables.containerversion')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_discussions', to='trackables.version')),
                ('versioned_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_discussions', to='trackables.versionedentity')),
            ],
            options={
                'ordering': ['-last_activity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(help_text='Main comment content (supports markdown)')),
                ('comment_type', models.CharField(choices=[('comment', 'Regular Comment'), ('note', 'Internal Note'), ('status_change', 'Status Change'), ('assignment', 'Assignment Change'), ('system', 'System Generated')], default='comment', max_length=15)),
                ('author', models.CharField(help_text='Username of comment author', max_length=100)),
                ('attachments', models.JSONField(blank=True, default=list, help_text="List of attachment info: [{'name': 'file.png', 'path': '/uploads/...', 'size': 1024}]")),
                ('mentions', models.JSONField(blank=True, default=list, help_text='List of mentioned usernames')),
                ('reactions', models.JSONField(blank=True, default=dict, help_text="Reactions: {'👍': ['user1', 'user2'], '❤️': ['user3']}")),
                ('is_edited', models.BooleanField(default=False)),
                ('edit_history', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='discussions.comment')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='discussions.discussion')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(help_text='Note content (supports markdown)')),
                ('note_type', models.CharField(choices=[('general', 'General Note'), ('todo', 'Todo Item'), ('reminder', 'Reminder'), ('issue', 'Issue Note'), ('review', 'Review Note'), ('documentation', 'Documentation')], default='general', max_length=15)),
                ('author', models.CharField(help_text='Username of note author', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('color', models.CharField(default='#ffeb3b', help_text='Hex color for note display', max_length=7)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.CharField(blank=True, max_length=100)),
                ('reminder_at', models.DateTimeField(blank=True, null=True)),
                ('is_reminded', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container_notes', to='trackables.container')),
                ('container_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container_version_notes', to='trackables.containerversion')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_notes', to='trackables.version')),
                ('versioned_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_notes', to='trackables.versionedentity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['versioned_entity'], name='discussions_version_13be1b_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['version'], name='discussions_version_5d48e5_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['container'], name='discussions_contain_99e3f9_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['container_version'], name='discussions_contain_e7c715_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['status', 'priority'], name='discussions_status_4c5b94_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['created_by'], name='discussions_created_69133c_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['discussion_type'], name='discussions_discuss_6cc873_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['last_activity'], name='discussions_last_ac_ffea5c_idx'),
        ),
        migrations.AddConstraint(
            model_name='discussion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('container__isnull', True), ('container_version__isnull', True), ('version__isnull', True), ('versioned_entity__isnull', False)), models.Q(('container__isnull', True), ('container_version__isnull', True), ('version__isnull', False), ('versioned_entity__isnull', True)), models.Q(('container__isnull', False), ('container_version__isnull', True), ('version__isnull', True), ('versioned_entity__isnull', True)), models.Q(('container__isnull', True), ('container_version__isnull', False), ('version__isnull', True), ('versioned_entity__isnull', True)), _connector='OR'), name='discussion_single_parent_constraint'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['discussion', 'created_at'], name='discussions_discuss_a69ec0_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author'], name='discussions_author_787cae_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['comment_type'], name='discussions_comment_52274f_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent_comment'], name='discussions_parent__d0eccb_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['versioned_entity'], name='discussions_version_fc3c00_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['version'], name='discussions_version_64c8fa_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['container'], name='discussions_contain_84589e_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['container_version'], name='discussions_contain_19874c_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['author'], name='discussions_author_90f9e6_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['note_type'], name='discussions_note_ty_62bde7_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['is_completed'], name='discussions_is_comp_ca5305_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['reminder_at'], name='discussions_reminde_a338b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('container__isnull', True), ('container_version__isnull', True), ('version__isnull', True), ('versioned_entity__isnull', False)), models.Q(('container__isnull', True), ('container_version__isnull', True), ('version__isnull', False), ('versioned_entity__isnull', True)), models.Q(('container__isnull', False), ('container_version__isnull', True), ('version__isnull', True), ('versioned_entity__isnull', True)), models.Q(('container__isnull', True), ('container_version__isnull', False), ('version__isnull', True), ('versioned_entity__isnull', True)), _connector='OR'), name='note_single_parent_constraint'),
        ),
    ]
